config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user do
    resources :people

  end

  
  root 'people#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :people 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #Kullanıcı giriş yapmalı.
  #Kullanıcı giriş yapmaz ise direkt olarak giriş ekranına yönlendirilecektir.
  before_action :authenticate_user!
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /people
  # GET /people.json
  def index
    #@people = Person.all
    @people = current_user.people.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
    @user = User.all
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to user_people_url, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to user_person_url, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to user_people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      #@user = User.find(params[:id])
      @person = Person.find(params[:id])
     
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :lastname, :phone, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="tr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
</p>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/people/_edit_form.html.erb
<%= simple_form_for(@person, url: user_person_path) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <%= form.input :name %>
    <%= form.input :lastname %>
    <%= form.input :phone %>
    <%= form.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
  

  </div>

   <div class="form-actions">
  

  
    <%= form.button :submit, "Ekle", class: 'button success' %>
  </div>
  
<% end %>

app/views/people/_form.html.erb
<%= simple_form_for(@person, url: user_people_path) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <%= form.input :name %>
    <%= form.input :lastname %>
    <%= form.input :phone %>
    <%#= form.hidden_field(:user_id, @current_user.id) %>
    <%= form.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
  

  </div>

   <div class="form-actions">
  

  
    <%= form.button :submit, "Ekle", class: 'button success' %>
  </div>
  
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'people/edit_form', person: @person %>

<%= link_to 'Show', user_person_path(@person) %> |
<%= link_to 'Back', user_people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.lastname %></td>
        <td><%= person.phone %></td>
        <td><%= link_to 'Show', user_person_path(current_user, person) %></td>
        <td><%#= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_user_person_path(current_user, person) %></td>
        <td><%#= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Destroy', user_person_path(current_user, person), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_user_person_path(current_user.id) %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', user_people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @person.lastname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @person.phone %>
</p>

<%= link_to 'Edit', edit_user_person_path(current_user, @person) %> |
<%= link_to 'Back', user_people_path %>